openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Health Health Get
  /licenses:
    get:
      summary: Get Licenses
      operationId: get_licenses_licenses_get
      responses:
        '200':
          description: Successful Response
          content:
            text/plain:
              schema:
                type: string

